### ISSUE TITLE
<APIError> code=-1100

### ISSUE THREAD

**Issue by AbeIgnocious** [adshao/go-binance#37]
Suddenly started getting the message: <APIError> code=-1100, msg=Illegal characters found in parameter 'interval'; legal range is '5, 10, 20, 50, 100, 500, 1000'.

```golang
snapshot, err := client.NewDepthService().Symbol(sym.Symbol).Limit(100).Do(context.Background())
```
Occurs for different all different legal ranges. However does not occur for every single time, and is not dependent on a specific pair.

**Comment by adshao** [comment]
Hi @AbeIgnocious , could you please try to reproduce it with `client.Debug = true`? and print the request url for the failed request.

**Comment by adshao** [comment]
hi @AbeIgnocious , I'm sorry I cannot reproduce it with `client.NewDepthService().Symbol("XEMETH").Limit(100).Do(context.Background())`
I got this error only if I change limit to an illegal value, for example, `Limit(110)`. Since limit is an optional param, could you just call without setting it. If it still happens, try to discuss it in telegram for binance api.

**Comment by AbeIgnocious** [comment]
So I have been retrying the script today, it seems to now only be related to the WRP pair. I suspect it is a maintenance error on the side of binance. Using this code I run a daemon process scraping the orderbook.
```golang
snapshot, err := client.NewDepthService().Symbol(sym.Symbol).Limit(100).Do(context.Background())
	if err != nil{
			if ! strings.Contains(sym.Symbol, "WPR") {
				Watch(gormdb, client, sym)
			} else {
				return
			}
		}
```

Will observe if the problem persists. For now closing the issue. Thanks for the check, adshao
